name: Temporary package verification

on:
  pull_request:
    paths:
      - '.github/workflows/packages.yml'
      - '.github/workflows/tmp-linuxdeploy-hash.yml'

permissions:
  contents: read

jobs:
  packages:
    uses: ./.github/workflows/packages.yml
